Url.create(long: "http://xkcd.com", short: "xkcd")
Url.create(long: "http://xojane.com", short: "xoj")
Url.create(long: "http://valleywag.gawker.com", short: "filth")
Url.create(long: "http://notcot.org", short: "art")
Url.create(long: "http://google.com", short: "find")